### ISSUE TITLE
[BUG][QUESTION] Binding site prediction is dependent on sequence length?

### ISSUE THREAD

**Issue by EdPym** [Jumitti/TFinder#31]
**Question**
When i search a ~5kb seq with a pwm i get 3 binding sites within a  specific 200bp window of that larger sequence. However when i run the same pwn on only that 200bp sequence i get 7. Any idea why the difference?

**Comment by Jumitti** [comment]
Hello :) 

I'm afraid I haven't understood correctly. Do you have a 5kb sequence and are you looking for a 200 bp pattern in it? then when you search in the 3 patterns found, TFinder finds 7 patterns in ?

If I understand correctly what is happening, I think it is due to the automatic threshold. The automatic threshold only allows up to -0.10 compared to the highest threshold. It depends on the generated matrices. 4 matrices are generated: sense, anti-sense, reverse, reverse-complement. the automatic threshold operates for each matrix. It is probably for these reasons that several results appear according to the inputs and the research.

Could you give more details? Sequence, pwm, threshold used, p-value etc... you can send me an email for more confidentiality minniti@ipmc.cnrs.fr

**Comment by Jumitti** [comment]
OK solution found ! 

Let's summarize the problem. for example, when we look for a pattern in a 5000 kb sequence, we find it found 10 times in the first 500 bp. When we recover these 500 bp we find more than 10 times the pattern. This is not normal.
The problem comes from the threshold setting. There was a problem in the script. It remained in automatic even when you set it manually.

The problem has been resolved and the correction implemented
[https://github.com/Jumitti/TFinder/commit/c85329d63de6c0f4eb11e1aa4a095dc4ce0dca30](url)
